//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Beijing.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BEIJING_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     129
#define IDB_BITMAP2                     130
#define IDB_BITMAP3                     131
#define IDB_BITMAP4                     132
#define IDB_BITMAP5                     133
#define IDB_BITMAP7                     135
#define IDB_BITMAP8                     136
#define IDB_BITMAP9                     137
#define IDB_BITMAP10                    138
#define IDB_BITMAP11                    139
#define IDB_BEIJINGMAP                  140
#define IDB_wukesong1                   141
#define IDB_andingmen1                  142
#define IDB_andingmen2                  143
#define IDB_bajiaocun1                  144
#define IDB_beijingzhan1                145
#define IDB_chaoyangmen1                146
#define IDB_chaoyangmen2                147
#define IDB_fuxingmen1                  148
#define IDB_gongzhufen1                 149
#define IDB_jianguomen1                 150
#define IDB_jianguomen2                 151
#define IDB_muxidi1                     152
#define IDB_pingguoyuan1                153
#define IDB_pingguoyuan2                154
#define IDB_qianmen1                    155
#define IDB_qianmen2                    156
#define IDB_qianmen3                    157
#define IDB_wangfujing1                 158
#define IDB_wangfujing2                 159
#define IDB_wangfujing3                 160
#define IDB_xidan1                      161
#define IDB_xidan2                      162
#define IDB_xidan3                      163
#define IDB_xidan4                      164
#define IDB_xizhimen1                   165
#define IDB_xizhimen2                   166
#define IDB_xizhimen3                   167
#define IDB_xizhimen4                   168
#define IDB_xuanwumen1                  169
#define IDB_xuanwumen2                  170
#define IDB_yonghegong1                 171
#define IDB_yonghegong2                 172
#define IDB_yonghegong3                 173
#define IDD_DIALOG1                     174
#define IDD_DIALOGBANK                  175
#define IDD_DIALOGLOAD                  176
#define IDD_RETURNMONEY                 177
#define IDD_DIALOGBUY                   178
#define IDD_DIALOGSELL                  179
#define IDD_DIALOGHOUSE                 180
#define IDD_DIALOGCARD                  181
#define IDD_HOSPITAL                    182
#define IDB_HOSPITAL                    183
#define IDD_DIALOGNOTEBOOK              186
#define IDB_NOTEBOOK                    187
#define IDD_DIALOGNEWS                  188
#define IDB_BITMAPNEWS                  189
#define IDB_BANK                        190
#define IDB_BITMAPHOUSE                 191
#define IDD_DIALOGRECORD                192
#define IDD_DIALOGNAME                  193
#define IDC_BANK                        1002
#define IDC_POST                        1003
#define IDC_HOUSE                       1004
#define IDC_CARD                        1005
#define IDC_HOSPITAL                    1006
#define IDC_NOTE                        1007
#define IDC_RADIO1                      1009
#define IDC_RADIO2                      1010
#define IDC_RADIO3                      1011
#define IDC_RADIO4                      1012
#define IDC_RADIO5                      1013
#define IDC_RADIO6                      1014
#define IDC_RADIO7                      1015
#define IDC_RADIO8                      1016
#define IDC_RADIO9                      1017
#define IDC_RADIO10                     1018
#define IDC_RADIO11                     1019
#define IDC_RADIO12                     1020
#define IDC_RADIO13                     1021
#define IDC_RADIO14                     1022
#define IDC_RADIO15                     1023
#define IDC_RADIO16                     1024
#define IDC_beijingfengjing             1025
#define IDC_DAY                         1026
#define IDC_Cash                        1027
#define IDC_Money                       1028
#define IDC_Health                      1029
#define IDC_Own                         1030
#define IDC_BUYNAME_BOX                 1031
#define IDC_BUYPRICE_BOX                1032
#define IDC_SELLNAME_BOX                1034
#define IDC_SELLPRICE_BOX               1035
#define IDC_BUY                         1036
#define IDC_SELL                        1037
#define IDC_SAVE                        1038
#define IDC_SPIN1                       1039
#define IDSAVE                          1040
#define IDC_LOAD                        1041
#define IDC_EDIT1                       1042
#define IDC_NAME                        1043
#define IDC_SELL_NAME                   1044
#define IDC_PRICE                       1045
#define IDC_SPIN2                       1046
#define IDC_NUM                         1047
#define IDC_0                           1048
#define IDC_1                           1049
#define IDC_2                           1050
#define IDC_3                           1051
#define IDC_4                           1052
#define IDC_5                           1053
#define IDC_6                           1054
#define IDC_7                           1055
#define IDC_8                           1056
#define IDC_NEWS                        1057
#define IDC_LIST_NAME                   1058
#define IDC_LIST_MONEY                  1059
#define IDC_RECORD                      1060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
